import{S as m,A as h,N as y}from"./assets/vendor-BuglDXfm.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))f(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&f(d)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function f(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();let u=null,a=null;function v(){window.innerWidth<1440?u||(u=new m(".how-swiper",{modules:[h],slidesPerView:1.7,spaceBetween:16,loop:!0,autoplay:{delay:3e3,disableOnInteraction:!1}})):u&&(u.destroy(!0,!0),u=null)}function L(){window.innerWidth<1440?a||(a=new m(".gallery-swiper",{modules:[h],slidesPerView:1.2,spaceBetween:16,loop:!0,autoplay:{delay:3e3,disableOnInteraction:!1}})):(a&&(a.destroy(!0,!0),a=null),a=new m(".gallery-swiper",{modules:[y],slidesPerView:3.5,spaceBetween:24,loop:!0,navigation:{nextEl:".gallery-next",prevEl:".gallery-prev"}}))}function g(){v(),L()}g();window.addEventListener("resize",()=>{clearTimeout(window.swiperResize),window.swiperResize=setTimeout(()=>{u&&(u.destroy(!0,!0),u=null),a&&(a.destroy(!0,!0),a=null),g()},200)});document.querySelectorAll(".faq-acc-el-trigger").forEach(l=>{l.addEventListener("click",()=>{const o=l.closest(".faq-acc-el"),c=o.querySelector(".faq-acc-el-descr-frame");o.classList.contains("open")?(o.classList.remove("open"),c.style.maxHeight="0"):(o.classList.add("open"),c.style.maxHeight=c.scrollHeight+"px")})});document.addEventListener("DOMContentLoaded",()=>{const l=document.querySelector(".menu-button"),o=l.querySelector(".icon"),c=document.querySelector(".modal"),f=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const d=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="24" height="24" rx="2" fill="#E8E5D6" />
  <path d="M6 8H17M6 16H17M6 12H17" stroke="#FFFFF3" stroke-linecap="square" />
</svg>
    `,n=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="24" height="24" rx="2" fill="#E8E5D6" />
  <path d="M8 8L12 12M12 12L8 16M12 12L16 16M12 12L16 8" stroke="#FFFFF3" stroke-linecap="square" stroke-linejoin="round" />
</svg>
    `;l.addEventListener("click",()=>{t=!t,o.innerHTML=t?n:d,t?i():r()}),f.forEach(p=>p.addEventListener("click",()=>{r(),o.innerHTML=d,t=!1})),window.addEventListener("scroll",s);function i(){c.style.display="block"}function r(){c.style.display="none"}function s(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function l(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const i=document.getElementById(n);if(!i)return;const r=l(),s=i.getBoundingClientRect().top+window.pageYOffset-r;window.scrollTo({top:s,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(i){const r=this.getAttribute("href");if(!r)return;const[s,p]=r.split("#");if(!p)return;const w=window.location.pathname.split("/").pop();!(s===""||s==="./"||s===w||s==="./"+w)||!document.getElementById(p)||(i.preventDefault(),o(p),t(p))})});const f=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(n){e.forEach(r=>r.classList.remove("active"));const i=document.querySelector(`.navigation-item a[href*="#${n}"]`);i&&i.closest(".navigation-item").classList.add("active")}function d(){const n=window.pageYOffset+l()+100;f.forEach(i=>{const r=i.offsetTop,s=r+i.offsetHeight;n>=r&&n<s&&t(i.id)})}if(window.addEventListener("scroll",d),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{o(n),t(n)},300)}});
//# sourceMappingURL=index.js.map
